# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'prac_mvp' do
pod 'SDWebImage', '~>3.7'
pod 'AFNetworking', '~> 3.0'
end

target 'prac_mvpTests' do

end

target 'prac_mvpUITests' do

end

